### ISSUE TITLE
ImportError: No module named stem.descriptor.remote

### ISSUE THREAD

**Issue by Sleepy-totem** [hephaest0s/creatorrc#3]
Ive done `pip install stem` and still cant use speetor.

Exact error line is:

> Traceback (most recent call last):
  File "creatorrc.py", line 194, in <module>
    torrc = arg_resolver[arg]()
  File "creatorrc.py", line 93, in speetor
    relays = download_descriptors()
  File "creatorrc.py", line 4, in download_descriptors
    from stem.descriptor.remote import DescriptorDownloader
ImportError: No module named stem.descriptor.remote

**Comment by yashupadhyay32** [comment]
same here... did you able to resolve it?
